// File generated by FlutterFire CLI.
// This is a placeholder - you'll need to run:
// flutter pub global activate flutterfire_cli
// flutterfire configure
// to generate the actual configuration for your project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0DeenONCCx8siIEs8StyP8woh5zTlwt0',
    appId: '1:19273889378:web:34fdea72eb1e61d0cb033b',
    messagingSenderId: '19273889378',
    projectId: 'mad2-finals',
    authDomain: 'mad2-finals.firebaseapp.com',
    storageBucket: 'mad2-finals.firebasestorage.app',
  );

  // Run 'flutterfire configure' to generate these values

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68rSfbJGOoSIGpSb6HHIEcw4l2audxo0',
    appId: '1:19273889378:android:3df4142b4cf3b7a9cb033b',
    messagingSenderId: '19273889378',
    projectId: 'mad2-finals',
    storageBucket: 'mad2-finals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm0cg8OxWuaSEgvTTWNIhUpQLVv_aPbn0',
    appId: '1:19273889378:ios:763df169434a09e6cb033b',
    messagingSenderId: '19273889378',
    projectId: 'mad2-finals',
    storageBucket: 'mad2-finals.firebasestorage.app',
    iosBundleId: 'com.example.frontend3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm0cg8OxWuaSEgvTTWNIhUpQLVv_aPbn0',
    appId: '1:19273889378:ios:763df169434a09e6cb033b',
    messagingSenderId: '19273889378',
    projectId: 'mad2-finals',
    storageBucket: 'mad2-finals.firebasestorage.app',
    iosBundleId: 'com.example.frontend3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0DeenONCCx8siIEs8StyP8woh5zTlwt0',
    appId: '1:19273889378:web:0da97544ad670fe4cb033b',
    messagingSenderId: '19273889378',
    projectId: 'mad2-finals',
    authDomain: 'mad2-finals.firebaseapp.com',
    storageBucket: 'mad2-finals.firebasestorage.app',
  );

}
