import 'package:flutter/material.dart';
// NOTE: You will need to run 'flutter pub add firebase_core'
//       and 'flutter pub add firebase_auth' in your terminal first.
// import 'package:firebase_core/firebase_core.dart'; // <--- ADD THIS
// import 'firebase_options.dart'; // <--- ADD THIS (Generated by FlutterFire CLI)

import 'login_page.dart';
import 'admin_dashboard.dart';
import 'products.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,

      // DEFAULT SCREEN
      initialRoute: "/login",

      // ROUTES
      routes: {
        "/login": (context) => LoginPage(),
        "/admin": (context) => AdminDashboard(),
        "/products": (context) => ProductsPage(),

      },
    );
  }
}
